DEBUG = False
SQLALCHEMY_ECHO = False
SERIALPORTBAUDRATE = 115200
UPLOAD_FOLDER = "uploads"
INTEGER_DIGITS_IN_DRILLFILE = 3
DECIMAL_DIGITS_IN_DRILLFILE = 3
GCODE_FLAVOUR = "G" # Possible values is (G)RBL, (M)arlin, (S)moothie
